### PR TITLE
Migrate to .Net 8

### PR DESCRIPTION
**Pull request by millicentachieng**
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1930

### CODE REVIEW

**Comment by millicentachieng** [comment]
Dependent on https://github.com/OneDrive/markdowndeep/pull/7

**Comment by millicentachieng** [comment]
Will update markdowndeep once https://github.com/OneDrive/markdowndeep/pull/7 is merged

**Review by andrueastman — APPROVED** [review]
Before we merge, there may be work needed to prevent breaking the pipelines. 

- https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/dev/pipelines/docs-permissions.yml
- https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/dev/pipelines/snippets.yml

**Comment by millicentachieng** [comment]
Thank you, @andrueastman. We have a PR https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1941 to update DevX API. I'll only merge this after that one has been reviewed and merged.

**Pull request merged**
