### PR TITLE
Validation Rule: Undescores are not allowed in file names

### PR DESCRIPTION
**Pull request by finsharp**
Error should be raised when file name contains underscore such as test_user.md.

All underscores should be converted to dashes '-' such as test-user.md.

Tests included to confirm behavior.

### CODE REVIEW

**Comment by finsharp** [comment]
@baywet We had added this validation rule to ensure files don't use underscores, I am wondering if this rule is still relevant?

**Comment by baywet** [comment]
@finsharp I can't tell you whether this is still relevant or not, but it's not conflicting anymore with the recent dotnet core migration.
 I'll defer to @BarryShehadeh to let us know whether it's still relevant.

**Comment by BarryShehadeh** [comment]
I honestly don't have enough background about the user scenarios and the reasoning behind the rule.
However, I know for a fact that our docs have tons of .md files with underscores, and we don't have a problem with it.

**Comment by baywet** [comment]
Thanks Barry
@MIchaelMainer any diverging opinion? or should we close that?

**Comment by MIchaelMainer** [comment]
@baywet Close it.

**Pull request closed without merging**
